apiVersion: webserver.mklug.at/v1alpha1
kind: Nginx
metadata:
  name: nginx-sample
spec:
  replicas: 3
  image: nginx
  message: "<h1>I am operator</h1>"
  ingress:
    enabled: true
    hostname: "host.docker.internal"
