apiVersion: webserver.mklug.at/v1alpha1
kind: Nginx
metadata:
  name: nginx-sample
spec:
  # Add fields here
  replicas: 3
  image: sadomasupilami/ba2-test:v1
  ingress:
    enabled: false
    hostname: "ba2-kubebuilder.cloud.mklug.at"
