apiVersion: webserver.mklug.at/v1alpha1
kind: Nginx
metadata:
  name: nginx-sample
spec:
  # Add fields here
  replicas: 3
  image: nginx
  ingress:
    enabled: false
    hostname: "ba2-kubebuilder.cloud.mklug.at"
